queries/useGroupQuery.ts
screens/Group.tsx
utils/keychain/helpers.ts

Updated to have some nicer handling for individual metadata Added handling to refresh on focused states

Caching Updates

---

android/app/src/main/res/values-night/colors.xml
components/Chat/Attachment/AddAttachmentButton.tsx
components/Chat/Input/Input.tsx
utils/i18n/strings.ts

Fixed by removing position absolute
Cleaned up some styles
Cleaned up colors
Fixes: https://github.com/ephemeraHQ/converse-app/issues/354

Fix: Android Attachment menu

---

ios/Podfile
ios/Podfile.lock
package.json
yarn.lock

bump XMTP Version

---

.github/workflows/build-internal.yml
app.json

Added env secrets when creating iOS internal builds
Update versions
Used no wait for builds

Fix for internal iOS builds 

---

data/helpers/messages/index.ts
data/store/framesStore.ts

Some frames did not unfurl even after being loaded once.
This fixes #160 and this should improve #333

Improve frames that were not hit from cache

---

screens/Group.tsx

Fixes Android Actionsheet colors

fix: Actionsheet color android

---

components/ConversationFlashList.tsx
components/ConversationList/GroupConversationItem.tsx
components/ConversationListItem.tsx
components/StateHandlers/NotificationsStateHandler.tsx
utils/attachment/helpers.ts
utils/conversation.ts

Closes out a remaining item from #71 ([Zeplin](https://zpl.io/6JNBzwd))

design feat: image previews in conversation list

---

components/AccountSettingsButton.tsx
components/ErroredHeader.tsx
data/store/accountsStore.ts
data/store/chatStore.ts
hooks/useShouldShowErrored.ts
screens/Accounts/Accounts.tsx
screens/Navigation/ConversationListNav.ios.tsx
screens/Profile.tsx
utils/i18n/strings.ts
utils/xmtpRN/sync.ts

Added error display for client errors
Show text to user on profile

feat: Added error display when client loading fails

---

queries/useGroupQuery.ts
utils/xmtpRN/conversations.ts

Reduces syncing on group, but relies on it to be successful when syncing the client

Reduce Syncing

---

screens/Main.tsx

wrongfully commented the profile page during onboarding

fix: reenable profile on onboarding

---

queries/useGroupConsentQuery.ts

Move back to useGroupQuery now that object is correctly made

fix: Consent Regression

---

package.json
yarn.lock

chore: Bump SDK

---

ios/Podfile.lock
queries/useGroupIsActive.ts
queries/useGroupNameQuery.ts
queries/useGroupPhotoQuery.ts
utils/xmtpRN/conversations.ts

Updated to set initial group data to avoid requests across bridge
Closes https://github.com/ephemeraHQ/converse-app/issues/463

Use Initial Group Data

---

App.tsx
components/ConversationList/NewConversationButton.tsx

mainly for simulator that doesn't detect shake the same way

Re-enable showing debug menu on long press new convo

---

.github/workflows/build-internal.yml
app.json

Updated to unique branch names

fix: Increment action

---

components/Chat/Chat.tsx

Recycling my own cells for my own messages, might fix #134 ?

Only recycle my own cells for my own messages

---

components/Chat/Frame/FramePreview.tsx
components/DebugButton.tsx
components/Onboarding/WarpcastConnect.tsx
data/store/accountsStore.ts
data/updates/asyncUpdates.ts
jest.setup.ts
queries/useClient.ts
screens/Accounts/Accounts.tsx
screens/Accounts/AccountsAndroid.tsx
screens/Group.tsx
screens/GroupLink.tsx
screens/Onboarding.tsx
screens/Onboarding.web.tsx
utils/api.ts
utils/attachment/index.ts
utils/evm/privy.ts
utils/logout/index.tsx
utils/mmkv.ts
utils/str.ts
utils/transaction.ts
utils/wallet.ts
utils/xmtpRN/conversations.ts
utils/xmtpRN/conversations.web.ts

Forgot some console.error in the code that now need to use our logger system

Use our logger for console.error

---

ios/Podfile
ios/Podfile.lock
package.json
yarn.lock

chore: Bump XMTP Version

---

components/ConversationList/GroupConversationItem.tsx
components/PinnedConversations/PinnedConversation.tsx
data/mappers.ts
data/store/chatStore.ts
ios/ConverseNotificationExtension/Datatypes.swift
queries/useGroupIsActive.ts
queries/useGroupNameQuery.ts
queries/useGroupPhotoQuery.ts
utils/xmtpRN/conversations.ts

Updated queries for Conversation List to set initial data updated at, and also not refetech on mount
Removed unused properties from state

Updated Queries

---

utils/reactions.ts

fix: Update translation import

---

components/Chat/Message/Message.tsx
components/Chat/Message/MessageActions.tsx
components/Chat/Message/MessageReactions.tsx
components/Chat/Message/MessageReactionsList.tsx
components/MessageContextMenuWrappers/MessageContextMenuWrapper.ios.tsx
components/MessageContextMenuWrappers/MessageContextMenuWrapper.tsx
components/MessageContextMenuWrappers/MessageContextMenuWrapperiOS.ios.tsx
components/MessageContextMenuWrappers/MessageContextMenuWrapperiOS.tsx
data/store/appStore.ts
ios/Podfile.lock
package.json
styles/sizes/index.ts
yarn.lock

Reactions Improvements with Context Menus

feat: Reactions Improvements 

---

containers/GroupScreenAddition.tsx
data/store/chatStore.ts

Added ability to delete group invites
Fixed snack not showing on first group invite creation

feat: Group Invites Delete

---

.github/workflows/build-internal.yml

We are now doing bugbash meetings at 4pm Pacific, so we should trigger the builds 2 hours earlier

Update schedule to trigger internal builds

---

utils/xmtpRN/sync.ts

We're seeing a lot of errors in Sentry
`Client error: storage error: Pool needs to  reconnect before use` 
This is because we're trying to do stuff with libxmtp but the libxmtp database connection has been disconnected when going into background.
Two possible reasons
- either the app is active again but the database connection didn't reconnect
- or the app is backgrounded but not yet suspended and we're retrying the sync process
This PR fixes both + tracks to Sentry the first case because it's not normal

If pool connection error while XMTP database is disconnected, let's reconnect

---

scripts/build/release_notes.sh

Added script for release notes

Release Notes Script

---

queries/useAddToGroupMutation.ts
queries/useAllowGroupMutation.ts
queries/useBlockGroupMutation.ts
queries/useGroupDescriptionMutation.ts
queries/useGroupNameMutation.ts
queries/useGroupPhotoMutation.ts
queries/usePromoteToAdminMutation.ts
queries/usePromoteToSuperAdminMutation.ts
queries/useRemoveFromGroupMutation.ts
queries/useRevokeAdminMutation.ts
queries/useRevokeSuperAdminMutation.ts

feat: Log mutation errors to sentry

---

components/MessageContextMenuWrappers/MessageContextMenuWrapper.tsx

Needed to move the reactions above the message and above the overlay being used by the menu

fix: Fix Android Menu

---

.github/workflows/build-internal.yml
scripts/build/incrementBuildNumbers.js

chore: Fix up workflow

---

screens/Navigation/ConversationRequestsListNav.tsx

Fixes #295 - [Back navigation from last accepted request](https://github.com/ephemeraHQ/converse-app/issues/295)

Navigate back to the main screen when no requests to display

---

components/Avatar.tsx
components/ConversationFlashList.tsx
components/ConversationList/GroupConversationItem.tsx
components/GroupAvatar.tsx
components/Indicator.tsx
components/PinnedConversations/PinnedConversation.tsx
utils/conversation/showUnreadOnConversation.ts

Added unread indicator on pinned chats
Added shared function for determining if unread should be shown Added Indicator component

feat: Unread indicators on Pinned Chats

---

components/Chat/Message/Message.tsx
components/Chat/Message/MessageActions.tsx
components/Chat/Message/MessageReactions.tsx
components/Chat/Message/MessageReactionsList.tsx
components/MessageContextMenuWrappers/MessageContextMenuWrapperiOS.ios.tsx
components/MessageContextMenuWrappers/MessageContextMenuWrapperiOS.tsx

fix: Reactions Floating

---

app.json
i18n/translations/en.ts
ios/Podfile
ios/Podfile.lock
package.json
screens/Profile.tsx
utils/conversation/showUnreadOnConversation.ts
utils/xmtpRN/client.ts
utils/xmtpRN/conversations.ts
yarn.lock

Added syncAllGroups call
Closes https://github.com/ephemeraHQ/converse-app/issues/543

feat: Added syncAllGroups

---

utils/notifications.ts

Fixed notification handling for Android
Fixes https://github.com/ephemeraHQ/converse-app/issues/373
Fixes https://github.com/ephemeraHQ/converse-app/issues/552

fix: Android Notification Linking

---

components/Chat/ChatPlaceholder/GroupChatPlaceholder.tsx
components/Chat/ConsentPopup/GroupConsentPopup.tsx
components/ConversationListItem.tsx
i18n/translations/en.ts

This PR addresses the last comments in:
- #559
- #315

View and restore flow update

---

components/Onboarding/UserProfile.tsx
screens/Main.tsx

Removed requirement
Closes https://github.com/ephemeraHQ/converse-app/issues/571

feat: Remove Profile Picture Requirement when onboarding

---

components/DebugButton.tsx
ios/Gemfile.lock
ios/Podfile.lock
package.json
yarn.lock

Closes https://github.com/xmtp/xmtp-react-native/issues/483

fix: sharing files from debug screen fixed so it works on iOS and Android

---

screens/Navigation/ConversationListNav.ios.tsx

Added color
Fixes https://github.com/ephemeraHQ/converse-app/issues/590

fix: Fix Connecting Dark mode

---

components/Onboarding/ConnectViaWallet.tsx
data/store/accountsStore.ts

If user gets into the state described in #563 this should mitigate it and unstuck user

fix: user weird currentAccount state

---

components/Recommendations/Recommendation.tsx
components/Recommendations/Recommendations.tsx
components/Search/NavigationChatButton.tsx
screens/NewConversation/NewConversation.tsx

Allow the user to see recommended profiles when creating a new group chat
Linked to: #346

Recommended profiles for new group chats

---

components/Avatar.tsx
components/Onboarding/UserProfile.tsx

Add placeholder for profile image

---

components/Avatar.tsx
components/Chat/Message/MessageReactions.tsx
styles/sizes/index.ts

Changed to Avatar rather than image
Added invert styling to avoid some black on black/white on white placeholders

fix: Placeholder avatar for reactors

---

components/MessageContextMenuWrappers/MessageContextMenuWrapper.tsx

Dismiss when copy and reply
Closes https://github.com/ephemeraHQ/converse-app/issues/585

feat: Dismiss context menu on reply and copy

---

utils/analytics.ts
utils/api.ts

Allows analytics to discriminate between App Store and TestFlight builds.
Server PR: https://github.com/ephemeraHQ/converse-backend/pull/25

feat: include version and build in analytics events

---

screens/GroupInvite.tsx

Closes #597 by matching the Proposed design below.

apply group invite styles

---

components/Chat/Message/Message.tsx

Added workaround from https://github.com/dominicstop/react-native-ios-context-menu/issues/9#issuecomment-1047058781
Fixes https://github.com/ephemeraHQ/converse-app/issues/607

fix: Context Menu Crash

---

ios/Podfile.lock
package.json
utils/logout/index.tsx
utils/xmtpRN/client.ts
yarn.lock

This will fix a few logout / relogin inconsistencies

Drop the client instance when logging out

---

components/ConversationList/ProfileSettingsButton.tsx
styles/sizes/index.ts

Removed style causing a change in height/width
Updated size enums
Closes https://github.com/ephemeraHQ/converse-app/issues/622

fix: Empty Profile Style

---

components/Connecting.tsx

Show connection error strings only to users with debug enabled

---

components/Chat/Message/MessageReactionsList.tsx

fix: Android Reactions Crash

---

components/ConversationListItem.tsx

Added longPress for Android component
Fixes https://github.com/ephemeraHQ/converse-app/issues/634

fix: Android Pinned Convos

---

components/Drawer.tsx
components/EmojiPicker/EmojiRow.tsx
components/EmojiPicker/EmojiRowList.tsx
containers/EmojiPicker.tsx

Better width and font scaling
Updated drawer to hide when keyboard shows

fix: Fixed styles for reactions drawer

---

screens/Navigation/ConversationListNav.ios.tsx

feat: share QR code from nav (iOS)

---

screens/GroupInvite.tsx
screens/Navigation/ShareProfileNav.tsx
screens/ShareProfile.tsx
styles/sizes/index.ts
utils/str.test.ts
utils/str.ts

feat: QR sharelink touchups

---

components/Button/Button.ios.tsx
screens/Navigation/ConversationListNav.ios.tsx

fix: qr button hitslop

---

components/Chat/Message/Message.tsx

- Removes logic that mistakenly hid MessageStatus from text messages
- Renames variables to improve component readability

fix: message sent status not showing

---

android/app/src/main/java/com/converse/dev/xmtp/Messages.kt
ios/ConverseNotificationExtension/Xmtp/Messages.swift

Check group consent to determine if a new group welcome should be shown This helps remove notifications when having a new installation being added after reinstall
Closes https://github.com/ephemeraHQ/converse-app/issues/631

feat: Remove Notifications for installation being added

---

components/MessageContextMenuWrappers/MessageContextMenuWrapper.tsx
components/MessageContextMenuWrappers/MessageContextMenuWrapperiOS.ios.tsx
utils/frames.ts

feat: share frame from context menu

---

app.config.ts
utils/xmtpRN/messages.ts

Redact message contents when on Production

Redact message contents

---

README.md
components/DebugButton.tsx
utils/logger.web.ts
utils/share.ts
utils/share.web.ts
utils/xmtpRN/client.web.ts
utils/xmtpRN/conversations.web.ts
utils/xmtpRN/logs.web.ts
utils/xmtpRN/sync.ts

Added some platform specific usage for Web
Updated ReadMe

fix: Fix Web

---

android/app/src/main/AndroidManifest.xml
screens/Navigation/GroupInviteNav.tsx
screens/Navigation/navHelpers.ts

Added handling for Android app links
Added changing link to new link pattern
Requires https://github.com/ephemeraHQ/converse-website/pull/8 for iOS

feat: Group Invite Universal Links

---

components/Chat/ChatGroupUpdatedMessage.tsx

fix: group update message styling & readability

---

screens/Navigation/ShareProfileNav.tsx

fix: sharenav darkmode bg

---

components/ConversationList/HiddenRequestsButton.tsx
components/ConversationList/RequestsButton.tsx
i18n/translations/en.ts
screens/Navigation/ConversationRequestsListNav.ios.tsx
screens/Navigation/ConversationRequestsListNav.tsx
styles/sizes/index.ts

Also contains refactoring and logic to display the notice message for requests and hidden requests
Closes #684

Requests UI: Spam becomes Hidden requests

---

components/Chat/Chat.tsx

Fixed up some smaller gains on rerender
Looks like the biggest issue is that initial mounting takes +300ms so this will likely not do too much for performance but reduces some renders
I'm pretty sure the ChatContext is really going to limit how much can be done, I don't think passing the entirety of the store in context is correct and should be using some state management and only selecting the messages when needed

fix: Conversation Performance

---

components/EmojiPicker/EmojiRow.tsx

Added some empty views to help space emojis nicer

fix: Empty Emoji styles

---

.github/workflows/check-ios-build.yml
ios/Podfile
ios/Podfile.lock
package.json
yarn.lock

Incorporates upstream change https://github.com/xmtp/libxmtp/pull/1041 which includes some streaming performance gains

Streaming improvements from libxmtp update

---

components/Chat/Frame/FramesPreviews.tsx
components/Chat/Message/MessageActions.tsx
utils/frames.ts

Frames were sometimes refetched in a loop, also too many urls were fetched

Improvements for frames rerendering

---

components/Chat/Attachment/AddAttachmentButton.tsx
components/Chat/Chat.tsx
components/Chat/ChatPlaceholder/ChatPlaceholder.tsx
components/Chat/ChatPlaceholder/GroupChatPlaceholder.tsx
components/Chat/ConsentPopup/ConsentPopup.tsx
components/Chat/ConsentPopup/GroupConsentPopup.tsx
components/Chat/Frame/FramePreview.tsx
components/Chat/Input/Input.tsx
components/Chat/Message/MessageReactions.tsx
components/Chat/Transaction/SendMoneyButton.tsx
components/Chat/Transaction/TransactionInput.tsx
components/Chat/Transaction/TransactionPreview.tsx
components/Recommendations/Recommendations.tsx
containers/EmojiPicker.tsx
utils/conversation.ts
utils/debug.ts

Another batch of optimizations
- react context selector was useless because we were using `pick` => changed to pick only one field at a time
- added a debug hook to print rerenders (useful when working on that stuff)
- removed unused dependencies that were causing rerenders as well

Fix conversation context, remove unused dependencies

---

components/Chat/Message/MessageActions.tsx
components/Chat/Message/MessageContextMenu.tsx
components/Chat/Message/MessageReactionsList.tsx
styles/sizes/index.ts
utils/contextMenu/constants.ts

- fixes horizontal positioning
- centers reactions display
- increases menu width
- normalizes spacing

JS context menu polish

---

android/app/src/main/java/com/converse/dev/BackendApi.kt
components/XmtpEngine.tsx
ios/ConverseNotificationExtension/Xmtp/Client.swift
utils/xmtpRN/api.ts

Fixes #635
Was blocked by https://github.com/xmtp/xmtp-react-native/pull/491/files but now works with that commit : https://github.com/ephemeraHQ/converse-app/pull/720/commits/8b91a8eaf8b5fc95a736d894fde4b46c87c82d2c so ready to merge
Also killing streams as soon as we leave might help with 0xdead10cc iOS crashes

group invite api key

---

assets/Encrypted.tsx
components/Onboarding/ConnectViaWallet.tsx
components/Onboarding/CreateEphemeral.tsx
components/Onboarding/OnboardingComponent.tsx
components/Onboarding/PrivateKeyConnect.tsx
components/Onboarding/PrivyConnect.tsx
components/Onboarding/Terms.tsx
components/Onboarding/UserProfile.tsx
components/Onboarding/ValueProps.tsx
components/Onboarding/WalletSelector.tsx
components/Picto/Picto.tsx
i18n/translations/en.ts
styles/colors/index.ts

Implements [design feedback](https://www.figma.com/design/p6mt4tEDltI4mypD3TIgUk/Converse-App?node-id=1867-13303&m=dev)

Styling for new onboarding copy

---

ios/Podfile
ios/Podfile.lock
package.json
yarn.lock

Includes the fix for plaintext headers.

Bump to the latest RN version

---

app.config.ts
data/store/chatStore.ts
utils/frames.ts
utils/str.ts
utils/xmtpRN/messages.ts

Fix frame display when just sent

---

components/Chat/Message/MessageActions.tsx
components/Chat/Message/MessageReactionsList.tsx
containers/EmojiPicker.tsx
data/store/chatStore.ts
screens/Conversation.tsx

We were rendering the emoji picker once per message. Rendering it only once for the whole convo for increased perf.

Render emojipicker only once

---

screens/GroupInvite.tsx

Fixed:
Consent was set only in protocol not in app
If group streams are broken group invite link did not redirect

Better group invite consent + handle even if streams dont work

---

components/Banner/AnimatedBanner.tsx
components/Banner/Banner.tsx
components/Chat/ChatNullState.tsx
components/Picto/Picto.tsx
config.ts
data/store/settingsStore.ts
i18n/translations/en.ts
screens/ConversationList.tsx
styles/sizes/index.ts

Reconciles with designs and introduces reusable banner component for future CTAs

Style null states according to designs

---

App.tsx
components/Onboarding/WalletSelector.tsx

This reverts commit 4e8b96352f1b70c3703346cb321b3bfaac45ec63.

Revert "WIP - Rainbow MWP support"

---

components/Chat/Message/Message.tsx

- Now using animations and useRef instead of state change that would trigger a message re-render
- Fixes dark mode render
- Fixes frame metadata rendering in loop
Linked to #696

Tap to reveal timestamps, date time and dark mode update

---

i18n/translations/en.ts
screens/NewConversation/NewGroupSummary.tsx

Update default group permissions

---

data/updates/asyncUpdates.ts
utils/frames.ts
utils/logger.ts
utils/navigation.ts

Helpers to read logs and match with screen recordings
Log navigation events
Also add app version on top of logs

Version & navigation logs

---

containers/EmojiPicker.tsx
utils/emojis/emojis.ts

Added 100 to hundred keywords
Updated to look in name and also match against emoji
Fixes https://github.com/ephemeraHQ/converse-app/issues/739

fix: Made emoji search a bit better

---

components/Chat/Message/MessageContextMenu.tsx
screens/Profile.tsx

fix: Cleanup android context menu

---

utils/xmtpRN/signIn.ts

Removed call to revoke on sign in
Closes https://github.com/ephemeraHQ/converse-app/issues/798

feat: Remove initial revocation

---

index.js
package.json
utils/perf/withRenderTime.tsx
wdyr.js
yarn.lock

Adds why did you render
Adds HOC for performance checks

feat: Why Did you Render

---

components/Onboarding/PrivateKeyConnect.tsx

fix: Added text input color

---

screens/GroupInvite.tsx

fix: Group Invite Nav

---

components/Chat/Message/MessageActions.tsx

Dismiss the animation when the context menu is shown Set shown only after scale animation
Focus input if the keyboard was being shown already
https://github.com/user-attachments/assets/8e59f72c-a177-4342-a9f5-e5b5294ed0bf

fix: Dismiss keyboard when focusing context menu

---

containers/EmojiPicker.tsx
package.json
yarn.lock

Added Match Sorter to manage search
Cleaned up some performance
Closes https://github.com/ephemeraHQ/converse-app/issues/821

feat: Emoji Search Improvements

---

components/EmojiPicker/EmojiRowList.tsx

Dismiss keyboard when emoji is actually tapped
Closes https://github.com/ephemeraHQ/converse-app/issues/836

fix: Added handled for persisting taps

---

.eslintrc.json
components/Chat/ChatPlaceholder/ChatPlaceholder.tsx
i18n/i18n.ts
i18n/translate.ts
package.json
yarn.lock

Fixed Import
Added lint rule to help avoid errors in the future as it's pretty easy to hit
Ignored areas where package import is expected
Fixes https://github.com/ephemeraHQ/converse-app/issues/845

fix: Translation Error

---

wdyr.js

`EXPO_PUBLIC_WDYR` need to be set to `true` in `.env` and `NODE_ENV` to `development`

Add env var to enable wdyr (why did you render)

---

components/DebugButton.tsx
ios/ConverseNotificationExtension/Spam.swift
ios/ConverseNotificationExtension/Xmtp/Messages.swift
ios/Podfile
ios/Podfile.lock
package.json
utils/xmtpRN/client.ts
utils/xmtpRN/signIn.ts
yarn.lock

Integrates latest SDK changes
See https://github.com/xmtp/xmtp-react-native/pull/503 and https://github.com/xmtp/xmtp-ios/pull/406

Upgrade SDK to fix group streaming issues

---

components/Chat/ChatNullState.tsx

fix: Remove Alpha Banner

---

scripts/build/update.js

Added eas.js script to read env variabls in

fix: OTA Updates

---

components/Onboarding/PrivyConnect.tsx

Fixed up styles for Dark mode
Closes https://github.com/ephemeraHQ/converse-app/issues/860

fix: Phone input styles for Dark mode

---

components/Onboarding/UserProfile.tsx

Added pressable around Avatar
Closes https://github.com/ephemeraHQ/converse-app/issues/861
cc @thierryskoda a small onboarding change

Make Avatar Clickable when onboarding

---

README.md
components/Chat/Frame/FramePreview.tsx

Updated to include button post url to follow frames spec
Closes https://github.com/ephemeraHQ/converse-app/issues/386

fix: Frames Post Handling

---

data/index.ts
utils/str.ts

fix: display lens handle and refresh if needed on load

---

i18n/translations/en.ts
screens/NewConversation/NewConversation.tsx

Allow group creation when 0 members are selected
Closes https://github.com/ephemeraHQ/converse-app/issues/857

feat: Enable Solo Group

---

i18n/translations/en.ts
screens/NewConversation/NewConversation.tsx

Reverts ephemeraHQ/converse-app#869

Revert "feat: Enable Solo Group"

---

app.config.ts
app.json
scripts/build/build.js
scripts/build/incrementVersion.js
utils/sentry.ts

Update version number
use shared version number instead of platform

chore: Update Version Number

---

components/PinnedConversations/PinnedConversation.tsx

Update to use the same query options as the rest of the list for now

fix: Query Alignment

---

components/Avatar.tsx
components/Indicator.tsx
components/__tests__/ActivityIndicator.test.tsx
components/__tests__/Avatar.test.tsx
components/__tests__/Button.test.tsx
components/__tests__/__snapshots__/ActivityIndicator.test.tsx.snap
components/__tests__/__snapshots__/Button.test.tsx.snap
package.json
yarn.lock

Added tests for Some shared components

feat: Component Tests

---

app.json
ios/Podfile
ios/Podfile.lock
package.json
yarn.lock

Bump SDK
Bump App Version for next build

chore: Bump Xmtp and App Versions

---

components/ConversationContextMenu.tsx

Add tap to dismiss conversation context menu

---

i18n/translations/en.ts

Removes references to the unfamiliar XMTP/MLS term "installation".

Updated revocation strings

---

ios/ConverseNotificationExtension/Xmtp/Client.swift

Safely unwrap a few keys
Log to Sentry when one fails
Closes https://github.com/ephemeraHQ/converse-app/issues/902

fix: DB Encryption Safety

---

utils/notifications.ts

Fixes https://github.com/ephemeraHQ/converse-app/issues/550

fix: Added null check for stringToHash

---

screens/Navigation/ConversationRequestsListNav.tsx

Remove Platform checks as there is an ios specific file: screens/Navigation/ConversationRequestsListNav.ios.tsx
Closes https://github.com/ephemeraHQ/converse-app/issues/678

feat: Remove Platform Checks

---

components/Chat/Attachment/AddAttachmentButton.tsx
components/Chat/Attachment/SendAttachmentPreview.tsx
components/Chat/Input/Input.tsx
data/store/chatStore.ts

Handle landscape attachments inside chat input

---

.github/workflows/build-app-release.yml
app.json
scripts/build/incrementVersion.js

Added App Release Action
Removed schedule on internal action
Increment app version for next build

chore: Update Build Scripts

---

.github/workflows/build-app-release.yml
app.json
scripts/build/incrementVersion.js

Increment Android build
Make Release notes

fix: Android Build Increment

---

.github/workflows/build-app-release.yml

fix: Increment step

---

app.json

This PR increments the buildNumber for iOS and the versionCode for Android.

Increment version numbers

---

components/Search/NavigationChatButton.tsx
i18n/translations/en.ts
screens/Navigation/ConversationListNav.tsx

Updated text for alert
Added selector for profile information
Added additional text to translations
Closes https://github.com/ephemeraHQ/converse-app/issues/872

feat: Informative Alert for non v3 Users

---

.github/workflows/build-internal.yml

Added some handling for Preview builds from build-internal

feat: Preview Build Scripts

---

eas.json

fix: Preview Builds

---

utils/retryWithBackoff.test.ts
utils/retryWithBackoff.ts
utils/wait.test.ts
utils/wait.ts
utils/xmtpRN/sync.ts

Added retryWithBackoff function
Added wait util
Added tests for both
Updated exported sync function to use retryWithBackoff Updated stream calls to retry if failed, but not attempt another retry Removed onSyncLost in sync function and move to an outer function to be called

fix: Syncing

---

.github/workflows/build-app-release.yml
app.json

fix: release notes script

---

.github/workflows/create-new-release.yml

Create new release branch action

feat: Create Release Branch Action

---

components/Chat/Chat.tsx
components/Chat/Message/Message.tsx
screens/Conversation.tsx
screens/NewConversation/NewGroupSummary.tsx

General Performance Cleanup for Conversation Screen Moved hardcoded arrays out of react context
Moved functions out of context
Memoize context value
useMemo on useStyles

fix: Performance Improvements for Conversation Screen

---

components/ConversationList/NewConversationButton.tsx
components/DebugButton.tsx
components/Onboarding/OnboardingComponent.tsx

Enable Debug Menu for all users
Removed some methods to be debug only
If a debug is not enabled, this menu will show:

feat: Enable Debug Menu for All

---

i18n/translations/en.ts
ios/ConverseNotificationExtension/NotificationService.swift
ios/ConverseNotificationExtension/Xmtp/Client.swift
screens/GroupInvite.tsx
utils/groupInvites.ts
utils/notifications.ts

When silent handling of group join requests failed then notify the user
Closes https://github.com/ephemeraHQ/converse-app/issues/982

feat: Notify When Group Join Fails

---

App.tsx

Performance improvements for App component
Moved constants out of React Context
Moved listeners inside of providers
Small useMemo usage

fix: Top level performance improvements

---

utils/navigation.ts

Updated handling to check if group invite
updated handling to check if group

fix: Add Group Invite and group links

---

components/Picto/Picto.tsx
screens/Navigation/ConversationNav.tsx

Corrected import for Android 
Removed import of gesture handler to avoid crash

fix: Small Fixes

---

android/app/src/main/java/com/converse/dev/PushNotificationsService.kt

fix: Android Push Notification parsing

---

package.json
scripts/test-deep-linking.js

Made this in a PR I abandoned but I thought this script could be still useful to test our deep linking

feat: test deep linking script

---

components/AccountSettingsButton.tsx
screens/Accounts/AccountsAndroid.tsx
screens/Main.tsx
screens/Navigation/ConversationListNav.tsx
screens/Navigation/SplitScreenNavigation/SplitLeftStackNavigation.tsx
utils/events.ts

Remove Android Drawer

---

components/Chat/Message/MessageReactions/MessageReactionsDrawer/MessageReactionsDrawer.tsx

Remove safe area insets that are not needed

Reactions drawer insets

---

components/Chat/ChatDumb.tsx
components/Chat/ChatGroupUpdatedMessage.tsx
components/Chat/Input/InputDumb.tsx
components/Chat/Message/V3Message.tsx
components/Conversation/V3Conversation.tsx
features/conversations/Messages.types.ts
features/conversations/utils/hasNextMessageInSeries.ts
features/conversations/utils/hasPreviousMessageInSeries.ts
features/conversations/utils/isLatestMessageSettledFromPeer.ts
features/conversations/utils/isLatestSettledFromCurrentUser.ts
features/conversations/utils/messageFromCurrentUser.ts
features/conversations/utils/messageShouldShowDateChange.ts
ios/ConverseNotificationExtension/Xmtp/Messages.swift
queries/useGroupMessages.ts
queries/useGroupQuery.ts
queries/useV3MessageItemQuery.ts
utils/message.ts

Added V3 Message and V3Message to Display
Added conversation context to help reduce overall changes

Conversation Context and V3Message

---

ios/Podfile.lock
utils/evm/external.ts

Fixing Coinbase Wallet external wallet autoconnect

fix: cbw autoconnect

---

design-system/Text/__tests__/Text.perf-test.tsx
design-system/Text/__tests__/Text.test.tsx
design-system/Text/__tests__/__snapshots__/Text.test.tsx.snap
design-system/test-utils/renderWithThemeProvider.tsx

Added Test for Text Design System component

feat: Text Design System Tests

---

components/Chat/Message/MessageReactions/MessageReactions.tsx
components/Chat/Message/MessageReactions/MessageReactionsDrawer/MessageReactionsDrawer.tsx

feat: use the $ pattern for the reaction bottom sheet styling

---

components/Chat/Message/MessageReactions/MessageReactions.tsx
components/Chat/Message/MessageReactions/MessageReactionsDrawer/MessageReactionsDrawer.tsx
design-system/BottomSheet/BottomSheetHeader.tsx
ios/Podfile.lock
utils/evm/external.ts

Merged Main into 2.0.9 Release Branch
Incremented Version

chore: Merged Main 

---

android/app/src/main/java/com/converse/Preferences.kt
android/app/src/main/java/com/converse/PushNotificationsService.kt
android/app/src/main/java/com/converse/Spam.kt
android/app/src/main/java/com/converse/xmtp/Client.kt
android/app/src/main/java/com/converse/xmtp/Conversations.kt
android/app/src/main/java/com/converse/xmtp/Messages.kt
components/V3DMListItem.tsx
components/V3GroupConversationListItem.tsx
data/store/chatStore.ts
features/conversation-list/hooks/useMessageIsUnread.ts
features/conversation-list/hooks/useMessageText.ts
features/conversation-list/hooks/useToggleReadStatus.ts

Fix Android Build
Update Conversation List to have hooks

fix: Android V3 Build

---

screens/NewAccount/NewAccountUserProfileScreen.tsx
screens/Onboarding/OnboardingUserProfileScreen.tsx
screens/UserProfileScreen.tsx

Fixed issues when saving a profile 'worked' and dismissed navigation
https://github.com/user-attachments/assets/c9f38bc8-d132-4ee6-8a52-1d41f6f33a01

fix: Saving Profile Error States

---

README.md
components/Chat/ChatGroupUpdatedMessage.tsx
components/ParsedText/ParsedText.tsx
components/PressableProfileWithText.tsx
components/__tests__/PressableProfileWithText.perf-test.tsx
package.json

Better handling when address is empty
Note: Handling for this changes in V3 work, so there shouldn't be cases of empty strings so didn't fix that

fix: Android Crashes

---

components/Chat/Input/Input.tsx

Add platform check for return key

fix: Sending on return key

---

queries/useAllowGroupMutation.ts
queries/useBlockGroupMutation.ts

These dead imports were preventing the app from building.

fix: Drop import of removed hook

---

App.tsx
components/Avatar.tsx
features/create-conversation/components/Chip.tsx
features/create-conversation/components/ComposerSection.tsx
features/create-conversation/components/MessageSection.tsx
features/create-conversation/components/PendingMembersSection.tsx
features/create-conversation/components/SearchResultsSection.tsx
features/create-conversation/components/index.ts
features/create-conversation/components/user-inline-search.tsx
features/create-conversation/create-conversation-screen.tsx
features/create-conversation/create-conversation.styles.ts
features/create-conversation/create-conversation.types.ts
features/search/components/ProfileSearchResultsList.tsx
features/search/components/SearchBar.tsx

handled most "musts" from https://github.com/ephemeraHQ/converse-app/issues/1498#issuecomment-2596110502
will wrap the rest up next week
https://www.loom.com/share/cee47d3644e341a4abacf0dcdf4df642?sid=03ee3626-f3f5-42cb-ade8-6b0b74c9c938

Create Conversation Design Feedback

---

features/conversation-requests-list/use-conversation-requests-list-items.tsx

Should resolve https://converse-app.sentry.io/issues/6227044314/?project=4504757120729088&query=is%3Aunresolved%20issue.priority%3A%5Bhigh%2C%20medium%5D&referrer=issue-stream&statsPeriod=24h&stream_index=15

fix: Request Errors from sentry

---

App.tsx
config.ts
jest.setup.ts
utils/logger.ts

I got tired of manually switching the logger color flag.
https://github.com/ephemeraHQ/converse-app-env/pull/5

Add env var for logger colors / types for logger colors/schemes

---

screens/Main.tsx
utils/navigation.ts

Removed old navigator function
Removed spam logs
Updated to createNavigationContainerRef

fix: Updates to navigator ref

---

.github/workflows/build-app-release.yml
.github/workflows/build-internal.yml

Updated to latest pull request action version

fix: Bumped create-pull-request action version

---

package.json
yarn.lock

Add required dependency back for release build

fix: Release build fix

---

screens/Main.tsx
utils/logout/index.tsx

feat: Logout and back to other accounts or onboarding

---

App.tsx
components/Screen/ScreenComp/Screen.tsx
design-system/BottomSheet/BottomSheetBackdropOpacity.tsx
design-system/Header/Header.tsx
design-system/Header/HeaderDemo.tsx
design-system/Icon/Icon.example.tsx
design-system/TextField/TextField.tsx
design-system/touchable-highlight.tsx
features/conversation-list/conversation-list-item/conversation-list-item-avatar-skeleton.tsx
features/conversation-list/conversation-list-item/conversation-list-item.tsx
features/conversation/conversation-composer/conversation-composer-container.tsx
features/conversation/conversation-composer/conversation-composer-reply-preview.tsx
features/conversation/conversation-composer/conversation-composer-send-attachment-preview.tsx
features/create-conversation/components/user-inline-search.tsx
features/create-conversation/create-conversation.styles.ts
theme/colorsDark.ts
theme/colorsLight.ts
theme/palette.ts
theme/useAppTheme.ts

Theme System:
- Update dark and light palette values to match design tokens
- Replace deprecated color values with new semantic tokens
- Add new background token: surfaceless
- Remove deprecated color tokens and references
- Removed `background.scrim` color, from the design system and the whole codebase
Reactions drawer:
- Update chip styles to use new semantic colors
- Improve touch feedback with proper underlayColor handling
- Remove redundant style properties
Loom: https://www.loom.com/share/4be4ec618c634785b2b0346527076b04
Linked to #1500

refactor: update color system, app-wide surface updates and TouchableHighlight behavior

---

components/animated-text-carousel.tsx
design-system/Text/AnimatedText.tsx

- Separate text animation and style handling
- Fix Android font weight string conversion
- Add proper type safety for styles
- Improve style merging logic
Tested with AnimatedTextCarousel & verified on Android

fix(AnimatedText): improve animation handling & fix Android font weights
