utils/shake.ts

The current shake detector seems to be killing perf
Never managed to make [react-native-shake](https://github.com/Doko-Demo-Doa/react-native-shake) work. Too bad because it's on the native thread
So trying in this PR to improve the current JS implementation perf. If it doesn't work we'll have to go for the long press on new conversation to show the debug menu, however the shake was useful to get debug logs during onboarding.

fix: improve shake perf

---

.github/workflows/build-internal.yml
scripts/build/eas.js

As discussed on Slack, the build action is missing a step to copy env variables to the eas config (as we do when we call locally yarn build), leading to no config being set

Add a step to copy over env variables when building through github

---

data/db/driver.ts

Fix for [that Sentry error](https://converse-app.sentry.io/issues/5667098779/?environment=prod&project=4504757120729088&query=is:unresolved+issue.priority:%5Bhigh,+medium%5D&statsPeriod=24h&stream_index=0&utc=true) which made my prod app crash.
I'm not 100% sure why we would call close on a closed db. Maybe if we leave and come back to the app fast. Anyways no need to close a closed db so I think this fix can work.

Prevent crashing if db is already closed

---

components/StateHandlers/NotificationsStateHandler.tsx

Less performant comparison but fixes the issue when going from consented to blocked and the convo list does not refresh.
In the future we  might change the way this method is called to improve perf

Fix: refresh convo list when consent changes

---

components/DebugButton.tsx

Show the app version inside the debug menu, especially useful during onboarding

Show app version in debug menu

---

components/Chat/Message/Message.tsx
components/Chat/Message/MessageActions.tsx
components/Chat/Message/MessageReactions.tsx
components/Chat/Message/MessageStatus.tsx

- Places reactions outside of bubbles for attachment, frame, and transaction messages
- Removes inconsistent borders, absolute positioning from all messages

feat: place reactions outside bubbles for attachments, frames, transactions

---

utils/xmtpRN/conversations.ts

Remove calls to start streaming again as this is fixed on the sdk side

remove restream setup for created groups

---

App.tsx
App.web.tsx
components/Button/Button.ios.tsx
components/Chat/Message/MessageActions.tsx

Not really sure what's going on, but have gotten reports for iOS not matching sometimes in dark moe
Changed all usage to default to light, Dark mode is normally the default but in a few cases there's a change it can return undefined or null

fix: Colors Sometimes changing

---

components/ConversationList/GroupConversationItem.tsx
components/ConversationListItem.tsx
i18n/translations/en.ts

After reviewing and testing yesterday's build v1.4.9 (246), I noticed that blocked (but not deleted) 1:1 conversations were showing up in the Removed Chats list.
I've now updated to allow unblocking directly from the Removed Chats view. The deleted conversations won't appear there, but at least you can now unblock the previously blocked peers from that list.
Please take a look at the [screenshot](https://github.com/user-attachments/assets/6950bfa9-a3a5-4bd0-82c6-66cecb297673) to see
Also fixed the UI only to show red buttons for destructive actions

Fix: allow to restore blocked users from the Removed Chat view

---

components/AccountSettingsButton.tsx
components/Chat/Attachment/AddAttachmentButton.tsx
components/Chat/Attachment/AttachmentMessagePreview.tsx
components/Chat/ChatPlaceholder/GroupChatPlaceholder.tsx
components/Chat/ConsentPopup/ConsentPopup.tsx
components/Chat/ConsentPopup/GroupConsentPopup.tsx
components/ConversationList/GroupConversationItem.tsx
components/ConversationListItem.tsx
components/Onboarding/ConnectViaWallet.tsx
containers/GroupPendingRequestsTable.tsx
containers/GroupScreenAddition.tsx
containers/GroupScreenConsentTable.tsx
containers/GroupScreenDescription.tsx
containers/GroupScreenImage.tsx
containers/GroupScreenMembersTable.tsx
i18n/translations/en.ts
screens/GroupInvite.tsx
screens/NewConversation/NewGroupSummary.tsx
tsconfig.json
utils/reactions.ts

Added tsconfig to handle index file
Changed all usage of translate to come from index file Fixes cases where first translation may show missing as it is being used before creating the i18n manager

chore: Clean up translations

---

components/XmtpEngine.tsx
data/db/driver.ts
data/db/index.ts
package.json
utils/appState.ts
utils/xmtpRN/sync.ts
yarn.lock

We saw cases where only group convos were showing
I suspect this is some db corruption introduced with the recent db disconnect feature because we save all group convos to db but only the 1:1 that are "new" so it would end up having only groups if there is a corruption
Tentative fix
- make sure we reconnect database even if hydration not done
- wait until app is back active before doing some critical database actions
- recover from a corruption by repulling all from network

Tentative fix for db corruption

---

components/Connecting.tsx
screens/Navigation/ConversationListNav.ios.tsx
screens/Navigation/ConversationListNav.tsx
utils/str.test.ts
utils/str.ts

Description:
- Warning Messages: Implemented warnings that inform users of potential issues during syncing or loading. On iOS, these messages appear when waiting for network, reconnecting, or syncing for more than 15 seconds
- String Shortening: Recycled a helper method to gracefully shorten strings in the navigation bar, preventing overflow when it becomes too populated
Impact:
1. Enhances UI clarity by managing long strings in the navigation bar.
2. Improves user awareness of app status during network or syncing issues.
Fixes #353 
**Screenshots**
Regular loading (below 15 seconds and without ongoing errors):
Reconnecting:
With long user name, shorten, as seen on iPhone 13 Mini (smallest screen width on iOS)
Waiting for network:

Improve iOS Navigation Bar and Syncing Error Handling

---

components/DebugButton.tsx
components/Onboarding/ConnectViaWallet.tsx
i18n/translations/en.ts
screens/Main.tsx
screens/Onboarding.tsx
screens/Onboarding.web.tsx
screens/Profile.tsx
utils/alert.ts
utils/fileSystem/index.ts
utils/xmtpRN/client.ts
utils/xmtpRN/signIn.ts
utils/xmtpRN/sync.ts

- When logging in, we want to revoke other installations because many of them are broken
- Also implements a check to logout user from other devices if installation has been revoked
- + check during onboarding if logging in with an existing libxmtp database but installation has been revoked
N.B. : due to the fact that we disconnect the XMTP db when leaving the app, I hit issues with `Client error: storage error: Pool needs to  reconnect before use` when coming back to the app after the revoke signature. 
Since this is a temporary debug feature for now, I implemented an ugly fix (reconnecting the database in this specific case when we leave the app). We can do that since during the onboading the db is not in the shared container.
But we will hit this kind of issues in the future:
- when …

Revoke other installations when logging in (temporary feature)

---

screens/NewConversation/NewConversation.tsx

Now hiding recommended profiles while creating a group chat. Closes #346

Stop showing recommended profiles while creating a group chat

---

styles/colors/index.ts

Updated inner color bubble color

fix: Android Dark mode inner bubble colors

---

hooks/useGroupPendingRequests.ts
screens/GroupInvite.tsx
utils/groupInvites.ts

Filter out requests that have already been approved but not updated on the backend Set storage so users can only attempt to join once from app installation perspective
Closes https://github.com/ephemeraHQ/converse-app/issues/584 
Closes https://github.com/ephemeraHQ/converse-app/issues/588

fix: Don't show pending requests for users already in the group

---

components/Onboarding/ConnectViaWallet.tsx
components/Onboarding/WalletSelector.tsx
components/XmtpEngine.tsx
utils/xmtpRN/signIn.ts

Seems that we have a regression on some onboarding infinite spinner
Trying to add more logs to see if it comes from us
It could also be an XMTP issue (I hit rate limiting once…) or a walletconnect issue (but I haven't managed to add wc specific logs yet)

Reorg and add logs to debug failing onboardings

---

components/Chat/Attachment/AttachmentMessagePreview.tsx
components/Chat/Message/MessageActions.tsx

This fixes the issue where frequently (but not always) long-pressing an image will both bring up the context menu and the preview.
I figured this might involve GestureDetector and ReanimatedTouchableOpacity onPress both firing, so moved the latter into a tap gesture. Tested this with an on-device development build and seems to fix the issue.

fix: image preview opening on long press

---

components/AccountSettingsButton.tsx
components/EphemeralAccountBanner.tsx
hooks/useDisconnectActionSheet.ts
i18n/translations/en.ts
screens/Profile.tsx

- Updates copy of ephemeral account banner to reflect deniability value prop: _"Disconnect to permanently remove your device from these conversations and ensure deniability."_
- Tap banner to logout and delete
- Only allow disconnect without delete if account is not ephemeral

feat: use ephemeral account for deniability

---

utils/set.test.ts
utils/set.ts
utils/xmtpRN/conversations.ts

We're seeing the app freeze frequently for users. On export it appears there is some performance issues with importing and listing conversations
Some stats
> 1:51:21 PM | DEBUG : [XmtpRN] Imported 846 exported conversations into client in 66.073s
> 1:51:36 PM | DEBUG : [XmtpRN] Listing 0 conversations for 0x2659aBe3F33c3BA20B9F440f24b746A22b1d53F7 took 14.756 seconds
> 1:51:37 PM | DEBUG : [XmtpRN] Listing 846 conversations for 0xf0EA7663233F99D0c12370671abBb6Cca980a490 took 81.935 seconds
This parallelizes some stuff during import and converts known topics to a set to help with performance.
The SDK lists 2k conversations in ~ 10s so 14 seconds to load 0 conversations looks like potentially an issue in this code somewhere.

Improve list conversation performance

---

utils/mmkv.ts

I was happy because I was having the "freeze on load" issue on my dev app
However I applied a stashed diff that was adding logs and **disabling the mmkv cache for react-query** and it went through without freezing anymore
So I deep dived on what could cause MMKV to freeze the app and found out this thread about memory leaks:
https://github.com/mrousavy/react-native-mmkv/issues/440
Basically, when you `mmkv.set("a", "test")` then again `mmkv.set("a", "test-2")`, by default, MMKV does not replace the first entry (this is by design, to be faster)
This makes the file grow kind of uncontrollably (by checking the thread and some chinese comments on the MMKV repo it seems at some point it should still pack the file but maybe it's getting too big too fast)
Another indicator that this might be the …

Perf MMKV: Avoid multiple writes to same key, use different instances zustand / react-query

---

queries/queryClient.ts

Kept digging on the app that freezes sometimes
From my latest PR : https://github.com/ephemeraHQ/converse-app/pull/656 I knew that the MMKV storage (for react-query) had smth to do with it. This has been confirmed in DEV, enabling / disabling the persistence for react-query causes / removes the freeze.
This PR disables `structuralSharing`
From the [react-query docs](https://tanstack.com/query/latest/docs/framework/react/guides/important-defaults#important-defaults), structuralSharing aims to improve perf, but
> If you are seeing performance issues because of large responses for example, you can disable this feature with the config.structuralSharing flag
I can confirm that on my failing dev env, this fixes the issue. However I don't know for how long!
Thoughts, cc @alexrisch 
- by adding …

Disable structural sharing

---

components/Chat/Message/Message.tsx

Adds a little spacing below the last message bubble in a series not from me

fix: message spacing for last in series not from me

---

components/Chat/Message/Message.tsx

Adds a little breathing room on the sides by increasing message padding to match iMessage.

fix: side margins around messages

---

components/DebugButton.tsx
data/db/datasource.ts
data/db/driver.ts
data/store/accountsStore.ts
ios/Podfile.lock
package.json
patches/@op-engineering+op-sqlite+6.0.1.patch
utils/keychain/helpers.ts

Encrypting the converse database 
- generating a salt on device and saving it to keystore
- using that salt + db encryption key when we generate a database
- setup plaintext header of 32 bytes to avoid 0xdead10cc crashes on iOS
- detect an unencrypted database, and migration to encrypt it
- path op-sqlite to be able to handle encrypted database AND unencrypted databases to be able to do the migration

Encrypt the converse database, including migrating an existing one

---

screens/Conversation.tsx

Recent optimizations prevented some rerenders after creating a convo (you wouldn't see changes in the convo including messages you just sent). Should fix #728

Fix rerender in new conversation streaming

---

eas.json

This will reduce the time it takes to build and the frequency of intermittent EAS build errors.

EAS build on larger workers

---

components/Chat/Message/Message.tsx
utils/date.ts

- Reveal message time on tap, also works when a date is already shown following a date change in message history
- Time displays are localized based on the 12/24-hour formats depending on the phone's locale
- Using Reanimated for animating height, keeping Animate from react native for the existing `<Swipable>` reply animation 
Closes #696

Tap to reveal timestamps

---

components/AccountSettingsButton.tsx
hooks/useDisconnectActionSheet.ts

Accounts can either be deleted from the profile page or from the accounts list. In both cases, an action sheet is shown to confirm the deletion. This action sheet was always deleting the current account, even if a different account was selected for deletion from the accounts list.

fix: delete wrong account

---

components/Chat/Frame/FramesPreviews.tsx
components/Chat/Message/MessageContextMenu.tsx
components/ConversationFlashList.tsx
components/ConversationList/GroupConversationItem.tsx
components/ConversationListItem.tsx
components/PinnedConversations/PinnedConversation.tsx
data/store/chatStore.ts
screens/Conversation.tsx
utils/conversation.ts
utils/conversationList.ts

A bunch of perf improvements based on latest QAs & logs
- prevent loop refetching of some frames by not refetching the frames for a given message id twice for the same "conversation display"
- prevent cell rerenders for conversationlistitem in multiple ways
- bad onLongPress
- navigation props updating should not cause rerenders => using a context with ref
- allowGroup missing parameters to not refetch for each row

Noe/frames & conversation list improvements

---

components/Onboarding/ConnectViaWallet.tsx
utils/logout/index.tsx

Might fix #775 but haven't reproduced on my end
Introduction of salt file was breaking our detection of 2 signatures needed so we didn't show the CTA to the user, so maybe the app was trying to trigger automatically a second signature and the OS was preventing it.
Let's see in next release if anyone still has the issues. Logs I have don't currently help.

Make sure to ask for user cta if no db files

---

components/Onboarding/UserProfile.tsx
i18n/translations/en.ts
utils/str.ts
vendor/humanhash.js

Thinking up a pseudonymous username is hard. This provides a generated default.
Future: make usernames optional for ephemeral accounts.

feat: default usernames for ephemeral accounts

---

components/Chat/Message/Message.tsx

- Allow tap to reveal time on message replies
- Disable tap to reveal time on attachments since it already opens a modal
Fixes #786

Tap to reveal timestamps updates

---

components/Recommendations/Recommendations.tsx
screens/NewConversation/NewConversation.tsx

Unhides matchmaker recommendations from the add group member modal. Many internal testers missed this when it was removed.

add recs back to add group member screen

---

ios/Converse/Info.plist

From App Store Review:
"One or more purpose strings in the app do not sufficiently explain the use of protected resources. Purpose strings must clearly and completely describe the app's use of data and, in most cases, provide an example of how the data will be used."
This PR:
- Updates purpose strings to provide the same level of detail as other messaging apps
- Removes permissions that are not currently used by the app

update camera and library purpose strings, remove unused permissions

---

ios/Converse/Info.plist

Today's submission was rejected because of a removed purpose string. This restores and adds back deleted purpose strings.

re-add removed purpose strings for submission

---

containers/GroupScreenAddition.tsx
i18n/translations/en.ts
screens/GroupInvite.tsx
utils/api.test.ts
utils/api.ts
utils/groupUtils/groupId.ts

Added handling for Group Ids on Group requests
Navigate the user to the screen when already joined
Inform the user the invite is no longer valid if they have been removed/group is not active
https://github.com/user-attachments/assets/b1aa14cd-e669-4b9d-a6c3-64ba134bc476

feat: Better Handling with Group invites

---

app.json

v2.0.0 was approved in App Store. To submit the new build that fixes group links, we need to bump to the next version.

Version bump to 2.0.1

---

components/ConversationFlashList.tsx
components/ConversationList/HiddenRequestsButton.tsx
data/helpers/conversations/spamScore.ts
screens/ConversationList.tsx
screens/Navigation/ConversationRequestsListNav.tsx
utils/conversation.ts
utils/events.ts
utils/xmtpRN/conversations.ts

Fixes for spam score and some android specific requests screen
- some clear spams were shown as non spam (1:1 conversations score was computed before we had the 1st message so we were not considering content)
- killing & reopening the app was making some hidden spam to show in likely not spam => undefined & null were not treated the same
- requests screen for android was freezing if many convos => a ConversationFlashList as a footer of another ConversationFlashList was breaking FlashList optimization. Fixed by showing the toggle as part of the flashlist and removing the Footer

perf improvement initial sync android + spam score fixes

---

babel.config.js
components/AnimatedBlurView.tsx
components/Chat/Chat.tsx
components/Chat/Message/MessageContextMenu.tsx
components/ConversationContextMenu.tsx
components/ConversationListItem.tsx
i18n/translations/en.ts
screens/ConversationReadOnly.tsx
tsconfig.json
utils/contextMenu/constants.ts

Conversation context menu implementation with auxiliary preview
Closes #727

Conversation context menu

---

components/Chat/Chat.tsx
screens/Conversation.tsx
screens/ConversationReadOnly.tsx

Refactor Chat component and optimize message handling for chat preview (long press on chat > auxiliary preview)
- Remove the `readOnly` props in the chat component, and create a dedicated, more lightweight `<ChatPreview />` component instead
- Extract `usePeerSocials`,  `renderItem` and `getItemType`
- Add optional `lastMessages` parameter in `getListArray` to limit the number of returned messages in `<ChatPreview />`
- Remove `readOnly` prop from `Chat` component, simplifying logic for padding and focus states
- Replace `ConverseChat` with the newly refactored `Chat` component
- Remove default export
- Remove unused code in `screens/ConversationReadOnly.tsx` (onLeaveScreen)
Linked to: https://github.com/ephemeraHQ/converse-app/pull/819#issuecomment-2379231954

Chat component refactor

---

data/store/chatStore.ts

Add type safety when setting spam score
Fixes https://github.com/ephemeraHQ/converse-app/issues/901

fix: Add some typesafety

---

components/Chat/Chat.tsx

fixes #910 
we are using a conversation key to force a full rerender in some specific cases but it was never adapted to groups (it used peerAddress rather than topic to handle 1:1 convos  pending creation / 1st message)

fix: convo key change when group members change

---

screens/Navigation/SplitScreenNavigation/SplitRightStackNavigation.tsx

Added Group Invite screen to SplitScreen navigation

fix: Group Invite screen on iPad

---

components/Avatar.tsx
containers/GroupPendingRequestsTable.tsx
hooks/usePreferredName.ts
hooks/usePreferredNames.ts
hooks/useProfileSocials.ts
hooks/useProfilesSocials.ts
i18n/translations/en.ts
package.json
queries/useProfileSocialsQuery.ts
yarn.lock

Added React Query Profiles query
Added batshit for batching queries
Added helper hooks
Lighter version of https://github.com/ephemeraHQ/converse-app/pull/633, just adds the queries/hooks for fetching profiles on demand rather than within syncing, but does not make any further changes

feat: Show Profile info in join requests

---

App.tsx
components/Chat/Chat.tsx
components/Chat/Input/Input.tsx
components/Chat/Input/InputReplyPreview.tsx
components/Chat/Message/Message.tsx
components/Chat/Message/MessageReactions.tsx
components/Chat/Transaction/TransactionInput.tsx
theme/borders.ts
theme/useAppTheme.ts

Implements rolled-up reactions
Closes #985 [Display reactions outside of the message bubble](https://github.com/ephemeraHQ/converse-app/issues/985)
Closes #937 [Rolled up reactions #937](https://github.com/ephemeraHQ/converse-app/issues/937)
Closes #667 [Fix overlapping transparent placeholder avatars in message reactions #667](https://github.com/ephemeraHQ/converse-app/issues/667)
After [Reactions detail drawer #938](https://github.com/ephemeraHQ/converse-app/issues/938) is done, tapping the rolled-up reactions button will open the reactions drawer, which will be included in another PR. For now and with this PR, tapping on the rolled-up reactions is not available, it's view-only.
Preview:

Rolled-up reactions

---

App.tsx
App.web.tsx
components/ExternalWalletPicker.tsx
components/XmtpEngine.tsx
data/db/index.ts
data/store/appStore.ts
utils/alert.ts
utils/appState/appStateIsBlurred.ts
utils/appState/waitUntilAppActive.ts

Refactored Xmtp Engine to be outside of React Context
Refactored Xmtp Cron to be outside of React Context
Adds subscriptions
Moves app state into folder and adds new app state utils

fix: Xmtp Engine Rerenders, Race Conditions, Crashes 

---

components/Chat/Message/MessageContextMenu.tsx
components/Chat/Message/MessageReactionsList.tsx
design-system/Text/Text.presets.ts

- Fix emoji picker emoji icons cut-off on Android Galaxy (tested from API 30 to 34 on 5 devices)
- Tested for iOS regression
- Migrate to the design system theme and apply the new emoji picker bubble design
Note: this closes #1146 – the rest of the `MessageContextMenu` component needs design system migration and refactor, I'll be working on this and submit it in another PR.

bugfix: emoji picker/reaction icons cut-off on Android

---

components/Chat/Frame/FramePreview.tsx

For some reason canOpenURL never returns for `ethereum:0x...` links
My guess is they're not `ethereum://something` and there is an incompatibility
This hotfix passes it directly to React Native's Linking lib

Fix linking for ethereum: links

---

components/Snackbar/Snackbar.store.ts
components/Snackbar/SnackbarBackdrop/SnackbarBackdrop.android.tsx
components/Snackbar/Snackbars.tsx

- Add null check for SnackbarBackdrop component to handle platform differences
- Initialize Zustand store on import to ensure store is ready before component renders
- Fix Android backdrop shadow by only rendering when snackbars are present
Closes #1229

fix: android backdrop shadow and initialization (snackbar)

---

features/GroupInvites/joinGroup/JoinGroupNavigation.tsx
features/GroupInvites/joinGroup/joinGroup.machine.ts
screens/Navigation/navHelpers.ts
utils/navigation.ts

Deep linking was causing crashes due to attempts to access the `routes` property in an undefined navigation state. This occurred because the navigation state wasn't properly initialized before processing URLs, and also, handling for such `inviteId` was missing.
Please verify/double check deep linking functionality for:
- Group invites
- DM links
- Regular group links
- Invalid/malformed links
Fixes [#1380](https://github.com/ephemeraHQ/converse-app/issues/1380)

Group invite deep link fix

---

features/conversation-list/conversation-list-loading.tsx
i18n/translate.ts

This PR improves the translate function's flexibility:
1. Type Changes:
- Allow both `TxKeyPath` and **plain English strings** as input
- Maintain type safety for known translation keys
- Enable direct use of English text when needed
2. Benefits:
- Simpler to use for one-off English strings
- No need to add translations for temporary or testing text
- Still maintains type-checking for actual translation keys

feat(i18n): allow plain English strings in translate function

---

features/conversation-requests-list/conversation-requests-list-segment-controller.tsx
features/conversation-requests-list/conversation-requests-list.screen.tsx
features/conversation/conversation-message/conversation-message-context-menu/conversation-message-context-menu-container.tsx
i18n/translations/en.ts
i18n/translations/fr.ts

This fixes an issue where the context menu on Android devices appeared at the wrong vertical position (too high).
Changes:
- Added status bar height consideration in MessageContextMenuContainer
- Adjusted the menu position calculation to offset for Android's status bar properly
- Replaced theme.layout.screen.height with useWindowDimensions for more accurate screen measurements
- Removed unused debugBorder import
Quick note: Fixed text cutoff issue in the segment controller on Android by adjusting the height from 32px to 36px and adding proper line height. This ensures the text "You might know" and "Hidden requests" are fully visible. ℹ️ This will need a complete refactor and new design, so I did this quick update.
Fixes #1591

fix: Android context menu position offset

---

containers/GroupPendingRequestsTable.tsx
features/conversation-list/hooks/use-delete-dm.ts
features/conversation-list/hooks/use-delete-group.ts
features/conversation/conversation-consent-popup/conversation-consent-popup-dm.tsx
features/conversation/conversation-consent-popup/conversation-consent-popup-group.tsx
features/conversation/conversation-consent-popup/conversation-consent-popup.design-system.tsx
features/groups/invite-to-group/invite-users-to-exisiting-group.screen.tsx
i18n/translations/en.ts
i18n/translations/fr.ts
utils/groupUtils/groupActionHandlers.ts

- Added full-width buttons in consent popups (DM and Group), removed icons
- Added helper text below delete button to inform about notification behavior
- Continued improving design system components for better reusability and consistency
- Created `ConversationConsentPopupHelperText` component in design system for consistent helper text styling
- Updated button and container components to support full-width layout
- Standardized spacing using theme values
- Centralized text alignment for helper messages
- Gradually removed unused translations
Linked to #1589

feat: New consent popup UI
